version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin#123
      MYSQL_DATABASE: myappdb

  wordpress:
    image: wordpress
    restart: always
    volumes:
      - ./wp_data:/var/www/html
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: myappdb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Admin#123
    depends_on:
       - db

volumes:
    db_data:
    wp_data: